Second Java HomeWork
globant-bootcamp/bootcamp-java-august-2021 pull request #13
Opened 2021-08-26 16:45 UTC by 1699kratos

## ISSUE:
First java homework from https://www.hackerrank.com/domains/java
Second Java HomeWork from https://www.hackerrank.com/domains/java

## FIX:
*Added more polymorphism in the main class.
*Create a class for each excercise  
*Create mini project
*Solved Java Inheritance I, II, and Output Formatting 
*Use of inheritance, encapsulation, and polymorphism, taking as an example vehicle classes.
*New Attendance 
*Created a Main class for vehicles
*Return string eith methods 
## EVIDENCES:
![image](https://user-images.githubusercontent.com/49655011/131202402-b0908bd0-97dd-47d4-b628-26290fc520bf.png)
![image](https://user-images.githubusercontent.com/49655011/131166799-5dad73c0-4dc2-4db1-847c-d052db334c13.png)
![image](https://user-images.githubusercontent.com/49655011/131002370-a2a13848-334f-405c-9cb6-7654d90dd3f4.png)
![image](https://user-images.githubusercontent.com/49655011/131002409-a82e7b62-d866-4dff-a253-a34af9c57ec1.png)
![image](https://user-images.githubusercontent.com/49655011/131160425-5c3ed6ce-5c28-421f-9fce-2886262b2ae9.png)
![image](https://user-images.githubusercontent.com/49655011/131160976-66b9fdc7-b6cc-4d8b-9e12-d44ca54eb7e3.png)

2021-08-28 03:32 UTC, edbermeo requested changes

2021-08-28 03:32 UTC, edbermeo commented on JavaErickHernandez/Day2/JavaFormatting.java
> +        System.out.println("================================");
Avoid the usage of magic strings

Magic Strings
https://deviq.com/antipatterns/magic-strings

2021-08-28 03:32 UTC, edbermeo commented on JavaErickHernandez/Day2/JavaFormatting.java
> +        System.out.println("================================");
Avoid the usage of magic strings

Magic Strings
https://deviq.com/antipatterns/magic-strings

2021-08-29 03:47 UTC, luisalanmz approved these changes
I liked your proposal to put evidence. Just answer the comments. You're doing well.

2021-08-29 06:12 UTC, edbermeo approved these changes
OK

2021-08-30 16:13 UTC, merged