Diego flores
globant-bootcamp/bootcamp-java-august-2021 pull request #14
Opened 2021-08-26 17:09 UTC by Dfloresa

2021-08-28 03:34 UTC, edbermeo requested changes

2021-08-28 03:34 UTC, edbermeo commented on DiegoFlores/if-else.java
> +        scanner.skip("(\r\n|[\n\r\u2028\u2029\u0085])?");
Avoid the usage of magic strings

Magic Strings
https://deviq.com/antipatterns/magic-strings

2021-08-28 03:34 UTC, edbermeo commented on DiegoFlores/if-else.java
> +            System.out.println("Weird");
Avoid the usage of magic strings

Magic Strings
https://deviq.com/antipatterns/magic-strings

2021-08-28 03:34 UTC, edbermeo commented on DiegoFlores/if-else.java
> +            System.out.println("Not Weird");
Avoid the usage of magic strings

Magic Strings
https://deviq.com/antipatterns/magic-strings

2021-08-28 21:20 UTC, Dfloresa reviewed
Magic strings Fixes

2021-08-29 06:16 UTC, edbermeo approved these changes

2021-08-29 12:59 UTC, luisalanmz approved these changes
LTGM

2021-08-29 18:37 UTC, merged