Sending Third Day challenges to review.
globant-bootcamp/bootcamp-java-august-2021 pull request #29
Opened 2021-08-27 19:24 UTC by UnCarro

2021-08-28 02:39 UTC, edbermeo requested changes
Add a .gitignore and exclude anything other than the code

2021-08-28 03:26 UTC, edbermeo requested changes

2021-08-28 03:26 UTC, edbermeo commented on Marco/Day03/hackerrank/Main.java
> +import hackerrank.solutions.*;
avoid the wildcard import

2021-08-28 03:26 UTC, edbermeo commented on Marco/Day03/challenge/src/challenge/Main.java
> +import challenge.classes.*;
Avoid the wildcard import

2021-08-28 03:26 UTC, edbermeo commented on Marco/Day03/hackerrank/solutions/Two.java
> +class Arithmetic{
Use a file per class

2021-08-28 03:26 UTC, edbermeo commented on Marco/Day03/hackerrank/solutions/Two.java
> +class Adder extends Arithmetic{
Use a file per class

2021-08-28 03:26 UTC, edbermeo commented on Marco/Day03/hackerrank/solutions/Two.java
> +public class Two{
Use a file per class

2021-08-28 03:26 UTC, edbermeo commented on Marco/Day03/hackerrank/solutions/Third.java
> +        System.out.println("================================");
Avoid magic strings

2021-08-28 03:26 UTC, edbermeo commented on Marco/Day03/hackerrank/solutions/Third.java
> +            System.out.printf("%-15s%03d%n", formatedString, formatedNumber);
Avoid magic strings

2021-08-28 03:26 UTC, edbermeo commented on Marco/Day03/hackerrank/solutions/Bird.java
> +public class Bird extends Animal {
Use a file per class

2021-08-28 03:26 UTC, edbermeo commented on Marco/Day03/hackerrank/solutions/Bird.java
> +class Animal {
Use a file per class

2021-08-28 03:26 UTC, edbermeo commented on Marco/Day03/hackerrank/solutions/Third.java
> +        System.out.println("================================");
Avoid magic strings

2021-08-28 16:54 UTC, luisod78 requested changes

2021-08-28 16:54 UTC, luisod78 commented on Marco/Day03/hackerrank/solutions/Third.java
> +        for(int i = 0; i < 3; i++)
Even when all programming books teach us for loops with var names like i, j, x, y, etc. please avoid these. All the time try to name your variables as descriptive as possible

2021-08-29 05:58 UTC, edbermeo requested changes

2021-08-29 05:58 UTC, edbermeo commented on Marco/Day03/hackerrank/solutions/Third.java
> +        int numOfIterations = 3;
Declare as a constant

2021-08-29 05:58 UTC, edbermeo commented on Marco/Day03/hackerrank/solutions/Third.java
> +        String decorator = "================================";
Declare as a constant

2021-08-29 06:24 UTC, edbermeo approved these changes
LGTM

2021-08-29 12:53 UTC, luisalanmz approved these changes
LGTM

2021-08-29 15:29 UTC, merged

2021-08-29 15:29 UTC, UnCarro commented
Thx!