Asistencia 26 y challenges
globant-bootcamp/bootcamp-java-august-2021 pull request #30
Opened 2021-08-27 19:26 UTC by LawlietLelouch03

2021-08-28 03:08 UTC, edbermeo requested changes
check code formatting and indentation

2021-08-28 03:08 UTC, edbermeo commented on VicenteDouriet/ChallengesDay26/Hackerrank/SolutionInheritance2.java
> +      System.out.println("My superclass is: Arithmetic");
this is hardcoded, what if I change the Arithmetic class name?
check 
getClass().getSimpleName()

2021-08-28 03:08 UTC, edbermeo commented on VicenteDouriet/ChallengesDay26/Hackerrank/SolutionInheritance2.java
> +class Arithmetic
Use a file per class

2021-08-28 03:08 UTC, edbermeo commented on VicenteDouriet/ChallengesDay26/Hackerrank/SolutionInheritance1.java
> +class Animal {
Use a file per class

2021-08-28 03:08 UTC, edbermeo commented on VicenteDouriet/ChallengesDay26/ChallengesClass/Employee.java
> +    public void printData(){
this can be extracted to an interface

2021-08-29 06:25 UTC, edbermeo commented
Please attend comments

2021-08-30 18:30 UTC, luisalanmz approved these changes
LGTM

2021-08-30 18:50 UTC, luisod78 commented on VicenteDouriet/ChallengesDay26/Hackerrank/SolutionInheritance1/Bird.java
> +class Bird extends Animal {
the default unnamed package should not be used

2021-08-30 18:50 UTC, luisod78 commented on VicenteDouriet/ChallengesDay26/ChallengesClass/Tester.java
> +public class Tester extends Employee {
the default unnamed package should not be used

2021-08-30 18:50 UTC, luisod78 commented on VicenteDouriet/ChallengesDay26/ChallengesClass/Printable.java
> +public interface Printable {
the default unnamed package should not be used

2021-08-30 18:50 UTC, luisod78 commented on VicenteDouriet/ChallengesDay26/ChallengesClass/Developer.java
> +public class Developer extends Employee {
the default unnamed package should not be used

2021-08-30 18:51 UTC, luisod78 commented on VicenteDouriet/ChallengesDay26/ChallengesClass/Company.java
> +public class Company {
the default unnamed package should not be used

2021-08-30 18:52 UTC, luisod78 commented on VicenteDouriet/ChallengesDay26/Hackerrank/SolutionPrintf/SolutionPrintf.java
> +        for (int i = 0; i < 3; i++) {
Variables names must be meaningful 

Avoid using magic numbers and magic strings

2021-08-31 03:37 UTC, closed without merging