mini project and hackerrank exercises - java oop
globant-bootcamp/bootcamp-java-august-2021 pull request #32
Opened 2021-08-27 22:16 UTC by mike-angek96

HackerRank exercises  and Mini project using in inheritance (Superclass and Subclass).  Java OOP

2021-08-28 03:18 UTC, edbermeo requested changes

2021-08-28 03:18 UTC, edbermeo commented on MiguelAngelVidalLiborio/Dia4-26Agosto/HackerRank/JavaInheritanceFirst.java
> +class Animal {
Use a file per class

2021-08-28 03:18 UTC, edbermeo commented on MiguelAngelVidalLiborio/Dia4-26Agosto/HackerRank/JavaInheritanceSecond.java
> +class Arithmetic {
Use a file per class

2021-08-28 03:18 UTC, edbermeo commented on MiguelAngelVidalLiborio/Dia4-26Agosto/HackerRank/JavaOutPutFormatting.java
> +		System.out.println("================================");
Avoid the usage of magic strings

Magic Strings
https://deviq.com/antipatterns/magic-strings

2021-08-28 03:18 UTC, edbermeo commented on MiguelAngelVidalLiborio/Dia4-26Agosto/MiniProject/javaoop/Main.java
> +		System.out.println("");
What is the functionality of this?

2021-08-29 03:50 UTC, luisalanmz approved these changes
LGTM . Just answer the comments

2021-08-29 06:29 UTC, edbermeo approved these changes

2021-08-30 19:05 UTC, merged