Sebastian Herrera sort folders and upload the challenges
globant-bootcamp/bootcamp-java-august-2021 pull request #33
Opened 2021-08-27 22:28 UTC by elrocetas

I sorted my folders and upload my challenges

2021-08-28 16:21 UTC, luisod78 commented on SebastianHerrera/bootcamp-java/src/main/java/hackerrank/day2/exercise1/Bird.java
> +package hackerrank.day2.exercise1;
Very good arranging your classes into packages
Great!

2021-08-28 16:21 UTC, luisod78 commented on SebastianHerrera/bootcamp-java/src/main/java/hackerrank/day2/exercise1/Bird.java
> +        System.out.println("I am singing Cielito Lindo");
Canta y no llores

2021-08-28 16:27 UTC, luisod78 requested changes

2021-08-28 16:27 UTC, luisod78 commented on SebastianHerrera/bootcamp-java/src/main/java/hackerrank/day2/exercise2/Operations.java
> +class Operations {
"1. A class named Arithmetic with a method named add that take 2 integers....."
"2. A class named Adder that inherits from....."

Operations???

2021-08-28 16:27 UTC, luisod78 commented on SebastianHerrera/bootcamp-java/src/main/java/hackerrank/day2/exercise3/Exercise3.java
> +        for (int i = 0; i < 3; i++) {
Even when all programing books include examples of for loops with var names like i, x, z, and so on, please avoid these.

HINT: (1 y 2) https://javarevisited.blogspot.com/2014/10/10-java-best-practices-to-name-variables-methods-classes-packages.html

2021-08-29 03:46 UTC, luisalanmz approved these changes
Ok

2021-08-29 05:47 UTC, edbermeo approved these changes
LGTM

2021-08-29 19:39 UTC, merged