Update list.txt
globant-bootcamp/bootcamp-java-august-2021 pull request #38
Opened 2021-08-29 15:23 UTC by JoseVm96

2021-08-29 22:59 UTC, luisalanmz requested changes
Just one suggestion

2021-08-29 22:59 UTC, luisalanmz commented on Attendance/list.txt
> +Vargas Martínez José de Jesús |25||26||27|
Try to put just one Pipe

2021-08-31 03:50 UTC, JoseVm96 commented on Attendance/list.txt
> +Vargas Martínez José de Jesús |25||26||27|
I’ll modify it in my next attendance.

2021-08-31 03:50 UTC, JoseVm96 commented on Attendance/list.txt
> +Vargas Martínez José de Jesús |25||26||27|
Thank you!

2021-08-31 17:01 UTC, luisalanmz approved these changes
OK

2021-09-08 20:40 UTC, globant-bootcamp approved these changes

2021-09-08 20:45 UTC, closed without merging