Attendance Challenge and hackerrank exercises of day 3
globant-bootcamp/bootcamp-java-august-2021 pull request #39
Opened 2021-08-29 18:06 UTC by davidgzu

[add] 
excercises of hacker Rank and challenge about heritance. polymorphism and  encapsulation

2021-08-29 20:11 UTC, edbermeo requested changes
Please use english everywhere! and check code formatting

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/PruebaFigura.java
> +        for (int i = 0; i < 3; i++) {
This is redundant. If you are defiying the array size as 3. just use figuras.length
Use meaningful var names **"i"**

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Figura.java
> +public abstract class Figura {
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Figura.java
> +    public abstract void calcularArea();
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Circulo.java
> +    public void calcularDiametro() {
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Circulo.java
> +    public void calcularArea() {
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Circulo.java
> +    public Circulo(String color, double radio) {
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Circulo.java
> +public class Circulo extends Figura {
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Circulo.java
> +    public Circulo() {
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Circulo.java
> +        double area = PI * Math.pow(radio, 2);
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Circulo.java
> +        double diametro = radio * 2;
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Circulo.java
> +        System.out.println("calculando diametro del circulo");
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Circulo.java
> +        String estado = "Circulo - color: " + color + ", " + "radio: " + radio + ", " + "área: " + area;
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Figura.java
> +    public String color;
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Figura.java
> +    public double area;
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Figura.java
> +    public Figura() {
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Figura.java
> +    public Figura(String color) {
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Figura.java
> +        this.color = color;
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/PruebaFigura.java
> +public class PruebaFigura {
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/PruebaFigura.java
> +        Figura[] figuras = new Figura[3]; // arreglo de referencias a figuras
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/PruebaFigura.java
> +                System.out.println("El objeto del indice " + i + " es un circulo.");
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Rectangulo.java
> +public class Rectangulo extends Figura {
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Rectangulo.java
> +    public double base;
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Rectangulo.java
> +    public double altura;
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Rectangulo.java
> +        System.out.println("Calculando el area del Rectangulo");
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Rectangulo.java
> +        String estado = "Rectangulo - color: " + color + ", " + "base: " + base + ", " + "altura: " + altura + ", "
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Triangulo.java
> +public class Triangulo extends Figura {
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Triangulo.java
> +    public double altura;
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Triangulo.java
> +        System.out.println("Calculando el area del triangulo");
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Triangulo.java
> +        String estado = "Triangulo - color: " + color + ", " + "base: " + base + ", " + "altura: " + altura + ", "
Use English!

2021-08-29 20:11 UTC, edbermeo commented on DavidGonzalezZumaya/Day3/HackerRank/OutputFormatting/OutputFormating.java
> +        for (int i = 0; i < 3; i++) {
Declare 3 as a constant and use meaningful var names **"i"**

2021-08-29 23:03 UTC, luisalanmz requested changes

2021-08-29 23:03 UTC, luisalanmz commented on DavidGonzalezZumaya/Day3/ChallengeDay3/PruebaFigura.java
> +        figuras[0] = new Triangulo("morado", 4.3, 8.6);
Put color name in English and in a Constant

2021-08-30 01:31 UTC, edbermeo approved these changes
LGTM!

2021-08-30 03:08 UTC, luisod78 requested changes

2021-08-30 03:08 UTC, luisod78 commented on DavidGonzalezZumaya/Day3/ChallengeDay3/Circle.java
> +public class Circle extends Figure {
The default unnamed package should not be used.
Try to arrange your classes into packages like:
com.bootcamp.dayone.excerciseone.....
or
com.inheritance.one.... two... etc

2021-08-30 18:54 UTC, luisod78 approved these changes

2021-08-30 18:57 UTC, merged