Diego flores
globant-bootcamp/bootcamp-java-august-2021 pull request #41
Opened 2021-08-29 19:58 UTC by Dfloresa

Added day 2 challenge

2021-08-29 23:08 UTC, luisalanmz requested changes

2021-08-29 23:08 UTC, luisalanmz commented on DiegoFlores/Day2/Challenge/Main.java
> +		Student student1 = new Student(000001,"architecture",1);
This string and all those that are in this class can go in constants

2021-08-30 03:21 UTC, luisod78 requested changes

2021-08-30 03:21 UTC, luisod78 commented on DiegoFlores/Day2/HackerRank/Inheritance1/Main.java
> +	public static void main(String[] args) {
Please fix identation

2021-08-31 04:45 UTC, Dfloresa reviewed
Fixed indentation and constant strings

2021-09-02 00:50 UTC, Dfloresa reviewed
Fixes done

2021-09-04 17:19 UTC, globant-bootcamp requested changes

2021-09-04 17:19 UTC, globant-bootcamp commented on DiegoFlores/Day2/Challenge/Main.java
> +    	public static final String STUDENT1CAREER = "architecture";
For the final name variables the words will need to by separeted by "_" example: STUDENT_ONE_CARRER, fix all the names

2021-09-04 17:19 UTC, globant-bootcamp commented on DiegoFlores/Day2/Challenge/Main.java
> +			student1.setNames("John");
What is the reason to not use the final variables that you alredy have? change all

2021-09-04 17:19 UTC, globant-bootcamp commented on DiegoFlores/Day2/Challenge/Person.java
> +
Remove whitespace

2021-09-04 17:19 UTC, globant-bootcamp commented on DiegoFlores/Day2/Challenge/Person.java
> +
Same

2021-09-04 17:19 UTC, globant-bootcamp commented on DiegoFlores/Day2/Challenge/Person.java
> +	private String surnames;
surnames? what is sur? improve the class name and use lowerCamelCase example userName

2021-09-04 17:19 UTC, globant-bootcamp commented on DiegoFlores/Day2/Challenge/Student.java
> +	private String	career;
Remove the extra space between String and carrer

2021-09-04 17:19 UTC, globant-bootcamp commented on DiegoFlores/Day2/Challenge/Student.java
> +
Remove whitespace

2021-09-04 17:19 UTC, globant-bootcamp commented on DiegoFlores/Day2/Challenge/Student.java
> +
Remove whitespace

2021-09-04 17:19 UTC, globant-bootcamp commented on DiegoFlores/Day2/Challenge/Teacher.java
> +
Remove whitespace

2021-09-04 17:19 UTC, globant-bootcamp commented on DiegoFlores/Day2/Challenge/Teacher.java
> +
Remove whitespace

2021-09-04 17:19 UTC, globant-bootcamp commented on DiegoFlores/Day2/HackerRank/Inheritance1/Animal.java
> +		System.out.println("I am walking");
Put this hardcode text inside a final static variable

2021-09-04 17:19 UTC, globant-bootcamp commented on DiegoFlores/Day2/HackerRank/Inheritance1/Bird.java
> +		System.out.println("I am flying");
Put this hardcode text inside a final static variable

2021-09-04 17:19 UTC, globant-bootcamp commented on DiegoFlores/Day2/HackerRank/Inheritance1/Bird.java
> +        System.out.println("I am singing");
Put this hardcode text inside a final static variable

2021-09-04 17:19 UTC, globant-bootcamp commented on DiegoFlores/Day2/HackerRank/Inheritance1/Main.java
> +		 Bird bird = new Bird();
Please fix identation

2021-09-04 17:19 UTC, globant-bootcamp commented on DiegoFlores/Day2/HackerRank/Inheritance2/Solution.java
> +        Adder a = new Adder();
Improve name variable

2021-09-04 20:25 UTC, Dfloresa reviewed
Fixes done

2021-09-04 20:32 UTC, Dfloresa reviewed
More fixes done in classes (indentation)

2021-09-08 20:35 UTC, globant-bootcamp approved these changes

2021-09-09 03:00 UTC, merged