Tania Gayosso
globant-bootcamp/bootcamp-java-august-2021 pull request #42
Opened 2021-08-29 21:48 UTC by taniagd

Changes in name of package and name of variables.

2021-08-29 23:10 UTC, luisalanmz requested changes

2021-08-29 23:10 UTC, luisalanmz commented on TaniaGayosso/HackerRank_August25/IfElse.java
> +		scanner.skip("(\r\n|[\n\r\u2028\u2029\u0085])?");
this string and all those that are in this class can go in constants

2021-08-30 03:26 UTC, luisod78 requested changes

2021-08-30 03:26 UTC, luisod78 commented on TaniaGayosso/HackerRank_August25/IfElse.java
> +package ChallengesOne;
Is not usual name a package with upper case letters. We can use Google Java Style Guide:
https://google.github.io/styleguide/javaguide.html#s5-naming
Please check 5.2.1

2021-08-30 18:43 UTC, closed without merging