Adriana cano
globant-bootcamp/bootcamp-java-august-2021 pull request #51
Opened 2021-08-31 16:22 UTC by AdrianaCR17

2021-08-31 17:17 UTC, luisalanmz requested changes
Please resolve conflict, I suggested one way to do it

2021-08-31 17:17 UTC, luisalanmz commented on .gitignore
> +<<<<<<< HEAD
You can resolve your conflicts, deleting this kinds of annotations

2021-08-31 20:35 UTC, luisalanmz approved these changes
Ok

2021-09-01 02:19 UTC, luisod78 approved these changes

2021-09-01 02:19 UTC, merged

2021-09-01 02:19 UTC, edbermeo approved these changes