Hackerrank3: java collection framework
globant-bootcamp/bootcamp-java-august-2021 pull request #52
Opened 2021-08-31 18:46 UTC by Ghumber

2021-09-01 04:02 UTC, globant-bootcamp requested changes

2021-09-01 04:02 UTC, globant-bootcamp commented on Humbertino_Avilez/Day3/Hackerrank/JavaSort.java
> +class Student implements Comparable<Object> {
extract this "class" in to a different file

2021-09-01 04:02 UTC, globant-bootcamp commented on Humbertino_Avilez/Day3/Hackerrank/JavaSort.java
> +	private String fname;
fname?

2021-09-01 04:02 UTC, globant-bootcamp commented on Humbertino_Avilez/Day3/Hackerrank/JavaSort.java
> +	private double cgpa;
cgpa?

2021-09-01 04:02 UTC, globant-bootcamp commented on Humbertino_Avilez/Day3/Hackerrank/JavaSort.java
> +	public int compareTo(Object o) {
o?

2021-09-01 04:02 UTC, globant-bootcamp commented on Humbertino_Avilez/Day3/Hackerrank/JavaArraylist.java
> +			String[] elements = sc.nextLine().split(" ");
Remplace all the hardcode String by static final variables

2021-09-01 06:11 UTC, globant-bootcamp approved these changes

2021-09-02 14:15 UTC, luisod78 approved these changes

2021-09-02 14:18 UTC, merged