day4: First Gradle with log4j and Hackerrank and attendance
globant-bootcamp/bootcamp-java-august-2021 pull request #64
Opened 2021-09-02 14:51 UTC by Ghumber

2021-09-02 15:03 UTC, luisod78 requested changes

2021-09-02 15:03 UTC, luisod78 commented on Humbertino_Avilez/Day4/Gradle_Hackerrank/NewGradle/lib/src/main/java/hackerrank/JavaInToString.java
> +	private static Logger javaLog = Logger.getLogger(Main.class);
I think logger var should be final
https://rules.sonarsource.com/java/tag/convention/RSPEC-1312

2021-09-02 17:30 UTC, luisod78 approved these changes

2021-09-03 04:36 UTC, luisalanmz approved these changes
OK

2021-09-03 04:48 UTC, merged