Java Collections & Attendance updating | Miguel A Valdes G
globant-bootcamp/bootcamp-java-august-2021 pull request #66
Opened 2021-09-02 20:22 UTC by MiguelAValdesG

Exercises of Java Collections from HackerRank done & updating of attendance list

2021-09-02 22:53 UTC, luisod78 requested changes

2021-09-02 22:53 UTC, luisod78 commented on MiguelAValdesG/Hackerrank/JavaArrayList.java
> +import java.util.ArrayList;
no package name?

2021-09-02 22:53 UTC, luisod78 commented on MiguelAValdesG/Hackerrank/JavaHashSet.java
> +    HashSet<String> stringPairs = new HashSet<>();
Always using interface type when declaring a collection
https://www.codejava.net/java-core/collections/18-java-collections-and-generics-best-practices

2021-09-02 22:53 UTC, luisod78 commented on MiguelAValdesG/Hackerrank/JavaHashSet.java
> +import java.util.HashMap;
no package name?

2021-09-02 22:53 UTC, luisod78 commented on MiguelAValdesG/Hackerrank/JavaHashTablesRansomNote.java
> +import java.io.BufferedReader;
no package name?

2021-09-02 22:53 UTC, luisod78 commented on MiguelAValdesG/Hackerrank/JavaHashTablesRansomNote.java
> +    HashMap<String, Integer> wordsInMagazine = new HashMap<>();
Always using interface type when declaring a collection
https://www.codejava.net/java-core/collections/18-java-collections-and-generics-best-practices

2021-09-02 22:53 UTC, luisod78 commented on MiguelAValdesG/Hackerrank/JavaHashTablesRansomNote.java
> +      Integer wordConcurrences = wordsInMagazine.get(word);
wordConcurrences??? you mean occurrences right???

The more meaningful your code, the more readable

2021-09-02 22:53 UTC, luisod78 commented on MiguelAValdesG/Hackerrank/JavaList.java
> +    LinkedList<Integer> list = new LinkedList<>();
Always using interface type when declaring a collection
https://www.codejava.net/java-core/collections/18-java-collections-and-generics-best-practices

2021-09-02 22:53 UTC, luisod78 commented on MiguelAValdesG/Hackerrank/JavaMap.java
> +    HashMap<String, Integer> phoneBook = new HashMap<>();
Always using interface type when declaring a collection
https://www.codejava.net/java-core/collections/18-java-collections-and-generics-best-practices

2021-09-03 02:28 UTC, luisod78 requested changes

2021-09-03 02:28 UTC, luisod78 commented on MiguelAValdesG/HackerRank/fundamentals/JavaInheritanceII.java
> +    // Create a new fundamentals.Adder object
please remove these comments

2021-09-03 02:28 UTC, luisod78 commented on MiguelAValdesG/HackerRank/collections/JavaHashTablesRansomNote.java
> +class Result {
Each class must be in its own file

2021-09-03 15:22 UTC, luisod78 approved these changes

2021-09-07 05:13 UTC, edbermeo approved these changes
LGTM!

2021-09-07 13:55 UTC, merged