Day5: First SpringBoot with Hackerrank and Attendance
globant-bootcamp/bootcamp-java-august-2021 pull request #68
Opened 2021-09-03 05:00 UTC by Ghumber

2021-09-03 16:08 UTC, luisod78 requested changes

2021-09-03 16:08 UTC, luisod78 commented on Humbertino_Avilez/Day5/First-spring-bootcamp/src/main/java/com/bolsadeideas/springboot/bootcamp/app/services/Implements/JavaPatternSyntaxCheckerImpl.java
> +		} catch (Exception exception) {
Prefer Specific Exceptions
https://dzone.com/articles/9-best-practices-to-handle-exceptions-in-java

2021-09-03 16:08 UTC, luisod78 commented on Humbertino_Avilez/Day5/First-spring-bootcamp/src/main/java/com/bolsadeideas/springboot/bootcamp/app/utils/Constans.java
> +public class Constans {
typo: Constants

2021-09-03 16:08 UTC, luisod78 commented on Humbertino_Avilez/Day5/First-spring-bootcamp/src/main/java/com/bolsadeideas/springboot/bootcamp/app/services/JavaAnagramsService.java
> +	public String isAnagram(String word, String anagram);
In Java when you see a method with prefix "is" means that method return a boolean.

2021-09-06 02:20 UTC, luisod78 requested changes

2021-09-06 02:20 UTC, luisod78 commented on Humbertino_Avilez/Day5/First-spring-bootcamp/src/main/java/com/bolsadeideas/springboot/bootcamp/app/controllers/HackerrankController.java
> +	JavaStringReverseService javaStringReverseService;
no access modifiers ?

2021-09-06 02:20 UTC, luisod78 commented on Humbertino_Avilez/Day5/First-spring-bootcamp/src/main/java/com/bolsadeideas/springboot/bootcamp/app/services/Implements/JavaAnagramsServiceImpl.java
> +				if (wordMap.containsKey(word.charAt(i))) {
There are 2 if-blocks almost identical... can you see??
only difference is the map is using... so, why don't declare a private method that receives a map and then.... 
follow me????

2021-09-07 23:24 UTC, luisod78 approved these changes

2021-09-07 23:24 UTC, luisod78 commented on Humbertino_Avilez/Day5/First-spring-bootcamp/src/main/java/com/bolsadeideas/springboot/bootcamp/app/utils/Constans.java
> +public class Constans {
you missed this comment

2021-09-07 23:24 UTC, luisod78 commented on Humbertino_Avilez/Day5/First-spring-bootcamp/src/main/java/com/bolsadeideas/springboot/bootcamp/app/services/JavaAnagramsService.java
> +	public String isAnagram(String word, String anagram);
so??? nothing to say? did u miss the comment?

2021-09-07 23:24 UTC, luisod78 commented on Humbertino_Avilez/Day5/First-spring-bootcamp/src/main/java/com/bolsadeideas/springboot/bootcamp/app/controllers/HackerrankController.java
> +	JavaStringReverseService javaStringReverseService;
missed this comment

2021-09-08 20:46 UTC, globant-bootcamp approved these changes

2021-09-08 21:01 UTC, merged