Hackerrank Arrays excercises added-GabySFB
globant-bootcamp/bootcamp-java-august-2021 pull request #72
Opened 2021-09-06 00:04 UTC by GabySFB

2021-09-06 02:33 UTC, luisod78 requested changes

2021-09-06 02:33 UTC, luisod78 commented on GabrielaRamirez/EjerciciosHackerrank/src/hackkerank/day3/JavaArrayList.java
> +        ArrayList[] set = new ArrayList[lines];
Code for interface not for implementation

2021-09-06 02:33 UTC, luisod78 commented on GabrielaRamirez/EjerciciosHackerrank/src/hackkerank/day3/JavaArrayList.java
> +            } catch(Exception e){
Prefer Specific Exceptions
https://dzone.com/articles/9-best-practices-to-handle-exceptions-in-java

2021-09-06 02:33 UTC, luisod78 commented on GabrielaRamirez/EjerciciosHackerrank/src/hackkerank/day3/JavaHashset.java
> +        HashSet<String> pairs = new HashSet<String>(t);
Code for interface not for implementation

2021-09-06 02:33 UTC, luisod78 commented on GabrielaRamirez/EjerciciosHackerrank/src/hackkerank/day3/ransomNote/MagazineNoteCheck.java
> +        for (String word:note){
I see missing whitespaces in almost all your code.... please refer to:
https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace

2021-09-06 02:33 UTC, luisod78 commented on GabrielaRamirez/EjerciciosHackerrank/src/hackkerank/day3/JavaMap.java
> +        for(int i=0;i<numberOfEntries;i++)
I see missing whitespaces in almost all your code.... please refer to:
https://google.github.io/styleguide/javaguide.html#s4.6.2-horizontal-whitespace

2021-09-08 20:48 UTC, globant-bootcamp approved these changes

2021-09-09 00:13 UTC, luisod78 requested changes

2021-09-09 00:13 UTC, luisod78 commented on GabrielaRamirez/EjerciciosHackerrank/src/hackkerank/day3/JavaHashset.java
> +        String[] pair_left = new String[t];
snake case???
Java prefers CamelCase for var names
https://google.github.io/styleguide/javaguide.html#s5.3-camel-case

2021-09-09 00:13 UTC, luisod78 commented on GabrielaRamirez/EjerciciosHackerrank/src/hackkerank/day3/ransomNote/MagazineNoteCheck.java
> +        for (String word:note){
you need an space before each '{'
you need an space between ':'

In your others classes you did it right!!!!!

2021-09-09 00:48 UTC, luisod78 approved these changes

2021-09-09 00:48 UTC, merged