Added Gradle Project with August 31 Exercises
globant-bootcamp/bootcamp-java-august-2021 pull request #87
Opened 2021-09-09 21:52 UTC by horacioAlva

2021-09-13 01:46 UTC, luisod78 requested changes

2021-09-13 01:46 UTC, luisod78 commented on Hackerrank Horacio Alvarado/Hackerrank Excercise(Gradle Project)/src/main/java/Hackerrank/August31/JavaCurrencyFormatter.java
> +import java.util.*;
No wildcard imports please
https://google.github.io/styleguide/javaguide.html#s3.3-import-statements

2021-09-13 01:46 UTC, luisod78 commented on Hackerrank Horacio Alvarado/Hackerrank Excercise(Gradle Project)/src/main/java/Hackerrank/August31/JavaIntToString.java
> +import java.util.*;
No wildcard imports please
https://google.github.io/styleguide/javaguide.html#s3.3-import-statements

2021-09-13 01:46 UTC, luisod78 commented on Hackerrank Horacio Alvarado/Hackerrank Excercise(Gradle Project)/src/main/java/Hackerrank/August31/JavaStaticInitializerBlock.java
> +import java.util.*;
No wildcard imports please
https://google.github.io/styleguide/javaguide.html#s3.3-import-statements

2021-09-16 23:20 UTC, edbermeo approved these changes
LGTM!

2021-09-17 18:06 UTC, merged