Spring JPA with JUnit
globant-bootcamp/bootcamp-java-august-2021 pull request #96
Opened 2021-09-12 08:43 UTC by Williiam8

2021-09-13 03:00 UTC, luisod78 requested changes

2021-09-13 03:00 UTC, luisod78 commented on WilliamsGarcia/02-09/vetCrud/src/main/java/com/example/vetcrud/service/impl/OwnerServiceImpl.java
> +            return null;
return null ?? dunno is OK....
even if you peek CrudRepository.delete() method, is a void method....

2021-09-13 03:00 UTC, luisod78 commented on WilliamsGarcia/02-09/vetCrud/src/main/java/com/example/vetcrud/service/impl/PetServiceImpl.java
> +            return null;
return null ??

2021-09-13 04:41 UTC, Williiam8 commented on WilliamsGarcia/02-09/vetCrud/src/test/java/com/example/vetcrud/VetCrudApplicationTests.java
> +    void contextLoads() {
In this case, I think yes, because I used mockito for test🧐

2021-09-13 14:37 UTC, globant-bootcamp requested changes

2021-09-13 14:37 UTC, globant-bootcamp commented on WilliamsGarcia/02-09/vetCrud/src/main/java/com/example/vetcrud/controller/PetController.java
> +import org.springframework.web.bind.annotation.*;
No wildcards please

2021-09-13 14:37 UTC, globant-bootcamp commented on WilliamsGarcia/02-09/vetCrud/src/main/java/com/example/vetcrud/entity/Pet.java
> +    @Column(name = "isVaccinated", nullable = false)
Use lower letters when naming columns. For separating words, use underscore https://www.sqlshack.com/learn-sql-naming-conventions/

2021-09-13 14:37 UTC, globant-bootcamp commented on WilliamsGarcia/02-09/vetCrud/src/main/java/com/example/vetcrud/service/impl/OwnerServiceImpl.java
> +import static com.example.vetcrud.utils.Constants.*;
No wildcards please

2021-09-13 14:37 UTC, globant-bootcamp commented on WilliamsGarcia/02-09/vetCrud/src/main/java/com/example/vetcrud/service/impl/PetServiceImpl.java
> +import static com.example.vetcrud.utils.Constants.*;
No wildcards please

2021-09-13 14:37 UTC, globant-bootcamp commented on WilliamsGarcia/02-09/vetCrud/src/test/java/com/example/vetcrud/controller/OwnerControllerTest.java
> +<<<<<<< HEAD
delete this

2021-09-13 14:37 UTC, globant-bootcamp commented on WilliamsGarcia/02-09/vetCrud/src/test/java/com/example/vetcrud/controller/OwnerControllerTest.java
> +=======
delete this

2021-09-13 14:37 UTC, globant-bootcamp commented on WilliamsGarcia/02-09/vetCrud/src/test/java/com/example/vetcrud/controller/OwnerControllerTest.java
> +>>>>>>> 2e9fd3d13785c741d87e3c001bb133b2d74ef9a4
same

2021-09-13 17:27 UTC, edbermeo approved these changes
LGTM!

2021-09-13 17:55 UTC, globant-bootcamp approved these changes

2021-09-14 20:29 UTC, lrod-glb approved these changes

2021-09-14 20:45 UTC, merged