Diego flores
globant-bootcamp/bootcamp-java-august-2021 pull request #98
Opened 2021-09-13 00:57 UTC by Dfloresa

Spring JPA, ExceptionHandler

2021-09-13 03:57 UTC, luisod78 requested changes

2021-09-13 03:57 UTC, luisod78 commented on DiegoFlores/SpringCRUD/src/main/java/com/bootcamp/vetPatitas/SpringCrudApplication.java
> +package com.bootcamp.vetPatitas;
https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names

2021-09-13 03:57 UTC, luisod78 commented on DiegoFlores/SpringCRUD/src/main/java/com/bootcamp/vetPatitas/config/ExceptionManager.java
> +package com.bootcamp.vetPatitas.config;
https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names

2021-09-13 03:57 UTC, luisod78 commented on DiegoFlores/SpringCRUD/src/main/java/com/bootcamp/vetPatitas/dao/PetDAO.java
> +package com.bootcamp.vetPatitas.dao;
https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names

2021-09-13 03:57 UTC, luisod78 commented on DiegoFlores/SpringCRUD/src/main/java/com/bootcamp/vetPatitas/dto/PetDTO.java
> +package com.bootcamp.vetPatitas.dto;
https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names

2021-09-13 03:57 UTC, luisod78 commented on DiegoFlores/SpringCRUD/src/main/java/com/bootcamp/vetPatitas/dto/ResponseDTO.java
> +package com.bootcamp.vetPatitas.dto;
https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names

2021-09-13 03:57 UTC, luisod78 commented on DiegoFlores/SpringCRUD/src/main/java/com/bootcamp/vetPatitas/entity/Pet.java
> +package com.bootcamp.vetPatitas.entity;
https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names

2021-09-13 03:57 UTC, luisod78 commented on DiegoFlores/SpringCRUD/src/main/java/com/bootcamp/vetPatitas/service/PetServiceImp.java
> +	PetMapper petMapper;
modifiers

2021-09-13 03:57 UTC, luisod78 commented on DiegoFlores/SpringCRUD/src/main/java/com/bootcamp/vetPatitas/service/PetServiceImp.java
> +	public PetDTO addPet(PetDTO petDTO) {
great!! you validate all input data

PS. Maybe you would like to read:
https://www.baeldung.com/javax-validation

2021-09-13 03:57 UTC, luisod78 commented on DiegoFlores/SpringCRUD/src/main/java/com/bootcamp/vetPatitas/userController/PetController.java
> +	@PutMapping(path = "/savePet",produces = MediaType.APPLICATION_JSON_VALUE)
Prefer nouns to name resources (path mapping)
https://restfulapi.net/resource-naming/

2021-09-13 03:57 UTC, luisod78 commented on DiegoFlores/SpringCRUD/src/test/java/com/bootcamp/vetPatitas/SpringCrudApplicationTests.java
> +	void contextLoads() {
a test without an assert?

2021-09-13 03:57 UTC, luisod78 commented on DiegoFlores/SpringCRUD/src/main/java/com/bootcamp/vetPatitas/service/PetServiceImp.java
> +	public PetDTO deletePet(PetDTO petDTO) {
Do you really need a DTO to delete a record??
only the id would be sufficient ?

2021-09-13 03:57 UTC, luisod78 commented on DiegoFlores/SpringCRUD/src/main/java/com/bootcamp/vetPatitas/service/PetServiceImp.java
> +		PetDTO petToBeDesabled = new PetDTO();
typo: desabled ?

2021-09-13 03:57 UTC, luisod78 commented on DiegoFlores/SpringCRUD/src/main/java/com/bootcamp/vetPatitas/exception/InvalidDataException.java
> +public class InvalidDataException  extends NullPointerException {
extends from NullPointerException???

you throw this Exception when input data is not correct... not when is null... right??

2021-09-15 04:37 UTC, Dfloresa reviewed
The corrections were done

2021-09-20 20:53 UTC, luisalanmz approved these changes
LGTM!

2021-09-20 20:56 UTC, merged